image:
  file: .gitpod.dockerfile
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
tasks:
  - init: python --version && python2.7 --version && virtualenv --version && ./mach build -r
    command: >
      ./mach run -r -z https://www.wikipedia.org -x -o test.png &&
      gp open test.png
